### ISSUE TITLE
Failed to activate the recent-files-fuzzy-finder package

### ISSUE THREAD

**Issue by forivall** [viddo/recent-files-fuzzy-finder#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.189.0
**System**: linux 3.18.10-1-MANJARO
**Thrown From**: [recent-files-fuzzy-finder](https://github.com/viddo/recent-files-fuzzy-finder) package, v0.1.1
### Stack Trace

Failed to activate the recent-files-fuzzy-finder package

```
At Module version mismatch. Expected 43, got 41.

Error: Module version mismatch. Expected 43, got 41.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/forivall/.atom/packages/recent-files-fuzzy-finder/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/home/forivall/.atom/packages/recent-files-fuzzy-finder/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/forivall/.atom/packages/recent-files-fuzzy-finder/lib/workspace-observer.coffee:2:15)
  at Object.<anonymous> (/home/forivall/.atom/packages/recent-files-fuzzy-finder/lib/workspace-observer.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.createRecentFiles (/home/forivall/.atom/packages/recent-files-fuzzy-finder/lib/main.coffee:21:27)
  at /home/forivall/.atom/packages/recent-files-fuzzy-finder/lib/main.coffee:10:8
  at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app/src/config.js:612:7)
  at Config.module.exports.Config.observe (/usr/share/atom/resources/app/src/config.js:126:21)
  at Object.module.exports.activate (/home/forivall/.atom/packages/recent-files-fuzzy-finder/lib/main.coffee:9:39)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:240:19)
  at /usr/share/atom/resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:461:21)
  at /usr/share/atom/resources/app/src/package-manager.js:445:29
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:343:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:440:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:423:46)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:622:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:52:25)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "adwaita-pro-ui",
      "tomorrow-ya"
    ],
    "projectHome": "/home/forivall/code/git",
    "disabledPackages": [
      "color-picker",
      "deprecation-cop",
      "symbols-view",
      "true-color",
      "remember-session",
      "tree-view-open-files"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      "__pycache__"
    ]
  },
  "recent-files-fuzzy-finder": {}
}
```
### Installed Packages

``` coffee
# User
adwaita-pro-ui, v0.30.1
atom-color-highlight, v3.0.8
atom-ctags, v2.6.1
autocomplete-plus, v2.7.1
ctags-status, v1.0.6
hide-files, v0.1.6
recent-files, v0.3.0
recent-files-fuzzy-finder, v0.1.1
save-session, v0.12.5
tomorrow-ya, v1.0.2

# Dev
No dev packages
```

**Comment by forivall** [comment]
Solved by reinstalling the package. Issue filed in case anyone else had this issue when upgrading atom.

**Comment by viddo** [comment]
Hey, thanks a lot for reporting!

For future reference (mental note to self): 
There is a dependency that requires to be compiled on the system ([pathwatcher](https://github.com/atom/node-pathwatcher)). It is actually included in [Atom](https://github.com/atom/atom/blob/master/package.json#L50), but unfortunately cannot be required by a package. 

An official Atom-dev claims that [dependencies are reused whenever possible](https://discuss.atom.io/t/if-i-already-have-pathwatcher-why-does-it-need-to-be-recompiled/14418/3), but that dependencies are still installed/compiled, so what seemed to happened here was that the already-built dependency didn't meet the minimum requirement of Atom/Node.

A reinstall might work because the dependency is compiled now matching the more recent version. It didn't work for me though, so I've updated the package (v0.1.2) so the offending dependency matches the "official" version used, it seems to do the trick.

Also [updated the README](https://github.com/viddo/recent-files-fuzzy-finder/blob/master/README.md#development) to contain info how to install node with a matching version of Atom.

**Comment by forivall** [comment]
Yeah, I could tell that the recompile is exactly what happened and what solved it, I just neglected to explain that; thanks for explaining the backstory.
