### ISSUE TITLE
Uncaught Error: Unable to watch path

### ISSUE THREAD

**Issue by forivall** [viddo/recent-files-fuzzy-finder#3]
1. From the command line, open a path that doens't exist.

**Atom Version**: 0.209.0
**System**: "Manjaro Linux"
**Thrown From**: [recent-files-fuzzy-finder](https://github.com/viddo/recent-files-fuzzy-finder) package, v0.1.3
### Stack Trace

Uncaught Error: Unable to watch path

```
At /usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:66

Error: Unable to watch path
  at Error (native)
  at HandleWatcher.start (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:179:12)
  at Directory.module.exports.Directory.subscribeToNativeChangeEvents (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:334:109)
  at Directory.module.exports.Directory.willAddSubscription (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:95:14)
  at Directory.willAddSubscription (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:3:61)
  at Directory.module.exports.Directory.onDidChange (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:89:12)
  at WorkspaceObserver.module.exports.WorkspaceObserver._updateProjectDirectoryObservers (/home/forivall/.atom/packages/recent-files-fuzzy-finder/lib/workspace-observer.coffee:24:43)
  at /home/forivall/.atom/packages/recent-files-fuzzy-finder/lib/workspace-observer.coffee:10:64
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.addPath (/usr/share/atom/resources/app.asar/src/project.js:274:29)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:41:32)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "adwaita-ui",
      "atomatigit",
      "command-toolbar",
      "ctags-status",
      "recent-files",
      "tomorrow",
      "atom-ctags",
      "git-projects",
      "welcome",
      "minimap-highlight-selected",
      "minimap-selection",
      "minimap",
      "autocomplete-plus-python-jedi",
      "atom-color-highlight",
      "atom-terminal",
      "linter-jshint",
      "sublime-tabs",
      "linter-clang"
    ],
    "themes": [
      "adwaita-pro-ui",
      "tomorrow-ya"
    ]
  },
  "recent-files-fuzzy-finder": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.0.0
adwaita-pro-ui, v1.0.0
color-picker, v2.0.4
custom-invisibles, v0.1.2
dbus, v0.0.1
docblockr, v0.7.2
editorconfig, v1.0.0
file-icons, v1.5.7
flow, v0.4.0
haxe, v0.6.1
hide-files, v0.1.7
highlight-selected, v0.9.3
ide-flow, v0.8.0
language-cmake, v0.1.3
language-diff, v0.3.0
language-haxe, v0.3.0
language-jade, v0.4.0
language-javascript-better, v1.5.0
language-json5, v1.1.0
language-qml, v1.0.0
linter, v0.12.6
linter-coffeelint, v0.3.2
linter-coffeescript, v0.2.1
linter-eslint, v0.5.8
linter-flake8, v1.4.2
linter-flow, v0.1.5
linter-pep8, v0.2.0
linter-pyflakes, v0.0.5
linter-pylint, v0.2.2
linter-rust, v0.1.0
linter-scss-lint, v1.0.4
linter-shellcheck, v0.0.8
linter-stylint, v0.6.0
project-manager, v1.15.10
project-view, v0.1.2
recent-files-fuzzy-finder, v0.1.3
run-in-terminal, v0.2.2
save-session, v0.15.5
selection-outlines, v0.2.0
symbols-tree-view, v0.9.3
tomorrow-ya, v1.0.2
tree-view, v0.172.0
tree-view-git-projects, v0.5.0
tree-view-open-files, v0.2.4
you-complete-me, v0.3.2

# Dev
No dev packages
```

**Comment by viddo** [comment]
Thx for reporting! I'll try to fix when I get a some time over

**Comment by forivall** [comment]
NP! It's pretty easy to work around for now, I just had to realize that i made a typo when trying to open a directory.
