### ISSUE TITLE
Uncaught TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by mikebronner** [viddo/recent-files-fuzzy-finder#33]
I renamed a file in the Project tree view.

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [recent-files-fuzzy-finder](https://github.com/viddo/recent-files-fuzzy-finder) package 0.6.0

### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:940

TypeError: path must be a string or Buffer
    at fs.stat (fs.js:940:11)
    at Object.fs.stat (ELECTRON_ASAR.js:291:16)
    at /packages/recent-files-fuzzy-finder/lib/recent-files.coffee:45:10
    at Array.forEach (native)
    at RecentFiles.module.exports.RecentFiles.removeDeleted (/packages/recent-files-fuzzy-finder/lib/recent-files.coffee:44:13)
    at /packages/recent-files-fuzzy-finder/lib/workspace-observer.coffee:24:74
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PathWatcher.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/directory.js:347:40)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:162:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at HandleWatcher.onEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:81:37)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:238:51
```

### Commands

```
  5x -2:34.7.0 editor:select-to-beginning-of-word (input.hidden-input)
     -2:33.7.0 core:delete (input.hidden-input)
     -2:26.1.0 core:paste (input.hidden-input)
     -2:25.7.0 intentions:highlight (input.hidden-input)
  8x -2:25.6.0 editor:move-to-beginning-of-word (input.hidden-input)
  5x -2:24 editor:select-to-beginning-of-word (input.hidden-input)
     -2:22.8.0 core:delete (input.hidden-input)
     -2:16.7.0 core:paste (input.hidden-input)
     -2:16.4.0 intentions:highlight (input.hidden-input)
  8x -2:16.3.0 editor:move-to-beginning-of-word (input.hidden-input)
  5x -2:14.7.0 editor:select-to-beginning-of-word (input.hidden-input)
     -2:13.5.0 core:delete (input.hidden-input)
     -2:06.3.0 core:paste (input.hidden-input)
     -2:01.8.0 core:backspace (input.hidden-input)
     -0:08.7.0 tree-view:move (span.name.icon.html5-icon.medium-orange)
     -0:05.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
autocomplete-js-import 1.4.0 
busy-signal 1.4.3 
chestnut-light-atom-syntax 0.2.1 
close-on-left 0.9.2 
dash 1.7.1 
double-tag 1.1.0 
duotone-light-syntax 2.1.0 
file-icons 2.1.18 
highlight-selected 0.13.1 
intentions 1.1.5 
language-blade 0.39.0 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-jsonlint 1.3.0 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-phpmd 2.0.0 
linter-sass-lint 1.8.3 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
pen-paper-coffee-syntax 0.14.9 
php-hyperclick 1.2.1 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.0 
recent-files-fuzzy-finder 0.6.0 
sort-lines 0.18.0 
symbols-navigator 1.4.0 
sync-settings 0.8.6 
tag 0.5.0 
tester 1.4.0 
tester-phpunit 1.0.6 
wakatime 7.0.4 
zentabs 0.8.9 
```

**Comment by viddo** [comment]
Thanks for reporting. Looks like the internal list have ended up in an invalid state somehow. I'll add some additional checks to avoid that from happening.

**Comment by mikebronner** [comment]
Thanks! I applied the update and things look to be working again. Thanks for the quick fix!!
